version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.4.2-node-browsers
    - image: postgres:9.4.1
      environment:
      - POSTGRES_USER=ubuntu

    environment:
      DISPLAY: :99
      RACK_ENV: test
    executor: docker
    working_directory: ~/canary-rails
    parallelism: 2
    steps:
    - checkout: {}
    - run: |
        sudo apt-get update
        sudo apt-get install -y qt5-default libqt5webkit5-dev \
          gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
        mkdir -p /tmp/artifacts/test_results
    - run:
        name: "install new rubygems: workaround bundler 1.16.0 bug"
        command: |
          gem update --system
    - run: |
        bundle install --path=vendor/bundle
    - run: |
        echo 'test:
          database: circle_ruby_test
          adapter: postgresql
          pool: 5
          timeout: 5000
          username: ubuntu
          host: localhost
        ' > config/database.yml && \
        bundle exec rake db:create db:schema:load
    - run: |
        TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings )
        echo TESTFILES: $TESTFILES
        # "--" is the Rspec separator between flags and the file list
        bundle exec rspec --color \
                          --require spec_helper \
                          --format RspecJunitFormatter \
                          --out /tmp/artifacts/test_results/rspec.xml \
                          --format progress \
                          -- \
                          $TESTFILES
        echo "contents" > /tmp/artifacts/test_results/some_file
        echo "<foo/>" > /tmp/artifacts/test_results/some_xml_file.xml
    - run:
        command: bundle exec rails test
        name: run a simple rails test (minitest)
    - store_test_results:
        path: /tmp/artifacts
    - store_artifacts:
        destination: build
        path: /tmp/artifacts
