version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.4.2
    - image: postgres:9.4.1
      environment:
      - POSTGRES_USER=ubuntu

    environment:
      DISPLAY: :99
      RACK_ENV: test
    executor: docker
    working_directory: ~/canary-rails
    parallelism: 2
    steps:
    - checkout: {}
    - run:
        background: true
        command: Xvfb :99 -screen 0 1280x1024x24
        name: Starting Xvfb (for Webkit)
    - run:
        command: |
          sudo apt-get update
          sudo apt-get install -y nodejs
          gem install bundler
          mkdir -p /tmp/artifacts/test_results
    - run:
        command: |
          bundle install
        shell: /bin/bash
    - run:
        command: |
          echo 'test:
            database: circle_ruby_test
            adapter: postgresql
            pool: 5
            timeout: 5000
            username: ubuntu
            host: localhost
          ' > config/database.yml && \
          bundle exec rake db:create db:schema:load
        shell: /bin/bash
    - run:
        command: |
          TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings )
          echo TESTFILES: $TESTFILES
          # "--" is the Rspec separator between flags and the file list
          bundle exec rspec --color \
                            --require spec_helper \
                            --format RspecJunitFormatter \
                            --out /tmp/artifacts/test_results/rspec.xml \
                            --format progress \
                            -- \
                            $TESTFILES
          echo "contents" > /tmp/artifacts/test_results/some_file
          echo "<foo/>" > /tmp/artifacts/test_results/some_xml_file.xml
    - store_test_results:
        path: /tmp/artifacts
    - store_artifacts:
        destination: build
        path: /tmp/artifacts
