version: 2
jobs:
  build_and_test_app:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.4.3
      - image: postgres:9.4.1
        environment:
        - POSTGRES_USER=ubuntu
    parallelism: 2
    environment:
      DISPLAY: :99
      RACK_ENV: test
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y qt5-default libqt5webkit5-dev \
              gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x xvfb

            curl -sL https://deb.nodesource.com/setup_8.x | bash -
            sudo apt-get install -y nodejs

            mkdir -p /tmp/artifacts/test_results

      - run:
          name: Start Xvfb
          background: true
          command: |
            Xvfb :99 -screen 0 1280x1024x24

      - run:
          name: "check pre-instaslled rubygems and bundler versions"
          command: |
            gem --version
            bundle --version
      #- run:
          #name: "install new rubygems: workaround bundler 1.16.0 bug"
          #command: |
            #sudo gem uninstall bundler --executables
            #sudo gem update --system
      - run: |
          bundle install --path=vendor/bundle
      - run: |
          echo 'test:
            database: circle_ruby_test
            adapter: postgresql
            pool: 5
            timeout: 5000
            username: ubuntu
            host: localhost
          ' > config/database.yml && \
          bundle exec rake db:create db:schema:load
      - run: |
          TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings )
          echo TESTFILES: $TESTFILES
          # "--" is the Rspec separator between flags and the file list
          bundle exec rspec --color \
                            --require spec_helper \
                            --format RspecJunitFormatter \
                            --out /tmp/artifacts/test_results/rspec.xml \
                            --format progress \
                            -- \
                            $TESTFILES
          echo "contents" > /tmp/artifacts/test_results/some_file
          echo "<foo/>" > /tmp/artifacts/test_results/some_xml_file.xml
      - run:
          command: bundle exec rails test
          name: run a simple rails test (minitest)
      - store_test_results:
          path: /tmp/artifacts
      - store_artifacts:
          destination: build
          path: /tmp/artifacts

workflows:
  version: 2
  build_image_and_test_app:
    jobs:
      - build_and_test_app
